<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
    function takeCssAdmin(){
        return $data = array(
            'css1'=>'themes/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css',
            'css2'=>'themes/adminlte/bower_components/font-awesome/css/font-awesome.min.css',
            'css3'=>'themes/adminlte/bower_components/Ionicons/css/ionicons.min.css',
            'css4'=>'themes/adminlte/dist/css/AdminLTE.min.css',
            'css5'=>'themes/adminlte/dist/css/skins/_all-skins.min.css',
            'css6'=>'themes/adminlte/bower_components/jvectormap/jquery-jvectormap.css',
            'css7'=>'themes/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css',
            'css8'=>'themes/adminlte/plugins/timepicker/bootstrap-timepicker.min.css',
            'css9'=>'themes/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css',
            'css10'=>'themes/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css',
            'css11'=>'https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css',
            'css12'=>'themes/adminlte/dist/css/jquery-ui.min.css',
            'css13'=>'themes/adminlte/bower_components/select2/dist/css/select2.min.css',
            'css14'=>'themes/adminlte/dist/css/message.css',
            'css15'=>'themes/adminlte/dist/sweetalert/sweetalert.css',
            'css16'=>'themes/adminlte/dist/css/loading.css',
            'css17'=>'themes/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css',
            'css18'=>'themes/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css',
            'css19'=>'themes/adminlte/plugins/iCheck/all.css',
            'css20'=>'themes/adminlte/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css',
        );
    }

    function takeJsAdmin(){
        return $data = array(
            'js1'=>'themes/adminlte/bower_components/jquery/dist/jquery.min.js',
            'js2'=>'themes/adminlte/dist/js/jquery-ui.min.js',
            'js3'=>'themes/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js',
            'js4'=>'themes/adminlte/bower_components/raphael/raphael.min.js',
            'js5'=>'themes/adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js',
            'js6'=>'themes/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js',
            'js7'=>'themes/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js',
            'js8'=>'themes/adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js',
            'js9'=>'themes/adminlte/bower_components/moment/min/moment.min.js',
            'js10'=>'themes/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js',
            'js11'=>'',
            'js12'=>'themes/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js',
            'js13'=>'themes/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js',
            'js14'=>'themes/adminlte/bower_components/fastclick/lib/fastclick.js',
            'js15'=>'themes/adminlte/dist/js/adminlte.min.js',
            'js16'=>'themes/adminlte/dist/js/demo.js',
            'js17'=>'themes/adminlte/dist/js/notify.min.js',
            'js18'=>'themes/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js',
            'js19'=>'themes/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js',
            'js20'=>'themes/adminlte/bower_components/datatables.net-bs/js/dataTables.colVis.js',
            'js21'=>'https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js',
            'js22'=>'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js',
            'js23'=>'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js',
            'js24'=>'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js',
            'js25'=>'https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js',
            'js26'=>'themes/adminlte/bower_components/select2/dist/js/select2.min.js',            
            'js27'=>'themes/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js',            
            'js28'=>'themes/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js',            
            'js29'=>'themes/adminlte/bower_components/select2/dist/js/select2.full.min.js',            
            'js30'=>'themes/adminlte/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js',            
            'js31'=>'themes/adminlte/plugins/timepicker/bootstrap-timepicker.min.js',            
        );
    }